export const ACTIONS = {
  JOIN: 'join',
  LEAVE: 'leave',
  SHARE_ROOMS: 'share-rooms',
  ADD_PEER: 'add-peer',
  ADD_CLIENT: 'add-client',
  UPDATE_CLIENT: 'update-client',
  REMOVE_PEER: 'remove-peer',
  RELAY_CLIENT: 'relay-client',
  RELAY_UPDATE_CLIENT: 'relay-update-client',
  RELAY_SDP: 'relay-sdp',
  RELAY_ICE: 'relay-ice',
  ICE_CANDIDATE: 'ice-candidate',
  SESSION_DESCRIPTION: 'session-description',
};
